### ISSUE TITLE
birth data from pesel

### ISSUE THREAD

**Issue by kristhina** [CodeForPoznan/alinka#24]
In the application pesel can begin only with the numbers 0, 1, 7, 8, 9.
When I added Pesel: 54021804547, everything was ok on the form, but the creation of documents failed.   The message was: "UnboundLocalError: local variable 'month' referenced before assignment"

**Comment by magul** [comment]
That's great task also to introduce tests (whenever @Rafalkufel will decide which test runner You going to use here).

**Comment by kristhina** [comment]
from pesel: 11020101242, I received the birth date: "01.-18.2011r."

**Comment by Rafalkufel** [comment]
Decision can be issued only for people younger than 23 yo. We're never going to issue decision for grandparents (and for parents either) :). @kristhina you did great work by discover that. Pesel of the people older than 23 years must be excluded. So pesel can start with '11' only when next cypher is '2' or '3'.
